SYNCQT.HEADER_FILES = ../../include/QtPCAP/qtpcap.h ../../include/QtPCAP/libpcap
SYNCQT.HEADER_CLASSES = ../../include/QtPCAP/QtPCAP
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.INJECTIONS = 
